[build]
  command = "npm run build"
  publish = "dist/public"

[dev]
  command = "npm run dev"
  targetPort = 5000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

## Route guestbook API to the Netlify Function
[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/guestbook"
  status = 200
