[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

## Route guestbook API to the Netlify Function
[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/guestbook"
  status = 200

[[redirects]]
  from = "/api/mal"
  to = "/.netlify/functions/mal"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
