[build]
  command = "npm run build"
  publish = "dist/public"

[dev]
  command = "npm run dev"
  targetPort = 8888

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

## Route guestbook API to the Netlify Function
[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/guestbook"
  status = 200

[[redirects]]
  from = "/api/mal-favorites"
  to = "/.netlify/functions/mal-favorites"
  status = 200

[[redirects]]
  from = "/api/mal-stats"
  to = "/.netlify/functions/mal-stats"
  status = 200

[[redirects]]
  from = "/api/spotify"
  to = "/.netlify/functions/spotify"
  status = 200
